import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateRiskReportPDF = (villageData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Header
    doc.setFillColor(14, 165, 233); // Blue
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text('Hydro Hub', 20, 20);

    doc.setFontSize(14);
    doc.setFont(undefined, 'normal');
    doc.text('Coastal Risk Assessment Report', 20, 30);

    // Village Information
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('Village Information', 20, 55);

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    doc.text(`Village: ${villageData.village.name}`, 20, 65);
    doc.text(`District: ${villageData.village.district}`, 20, 72);
    doc.text(`State: ${villageData.village.state}`, 20, 79);
    doc.text(`Date: ${new Date(villageData.last_updated || Date.now()).toLocaleDateString()}`, 20, 86);

    // Overall Risk Score
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Overall Risk Assessment', 20, 100);

    const riskScore = villageData.overall_risk_score;
    const riskCategory = riskScore >= 76 ? 'EXTREME' :
        riskScore >= 51 ? 'HIGH' :
            riskScore >= 26 ? 'MODERATE' : 'LOW';

    doc.setFontSize(14);
    doc.text(`Risk Score: ${riskScore}/100`, 20, 110);
    doc.text(`Risk Category: ${riskCategory}`, 20, 120);

    // Individual Risk Scores Table
    doc.autoTable({
        startY: 130,
        head: [['Risk Type', 'Score (0-100)']],
        body: [
            ['Flood Risk', (villageData.risk_scores?.flood || 0).toString()],
            ['Cyclone Risk', (villageData.risk_scores?.cyclone || 0).toString()],
            ['Rainfall Risk', (villageData.risk_scores?.rainfall || 0).toString()],
            ['Erosion Risk', (villageData.risk_scores?.erosion || 0).toString()]
        ],
        theme: 'grid',
        headStyles: { fillColor: [14, 165, 233] }
    });

    // Environmental Data Table
    const finalY1 = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Environmental Indicators', 20, finalY1);

    doc.autoTable({
        startY: finalY1 + 5,
        head: [['Indicator', 'Value (0-10 scale)']],
        body: [
            ['Sea Level Rise', (villageData.environmental?.sea_level_rise || 0).toString()],
            ['Cyclone Frequency', (villageData.environmental?.cyclone_frequency || 0).toString()],
            ['Storm Surge Height', (villageData.environmental?.storm_surge_height || 0).toString()],
            ['Erosion Rate', (villageData.environmental?.erosion_rate || 0).toString()],
            ['Extreme Rainfall', (villageData.environmental?.extreme_rainfall || 0).toString()]
        ],
        theme: 'grid',
        headStyles: { fillColor: [20, 184, 166] }
    });

    // Add new page for settlement data
    doc.addPage();

    // Settlement Data Table
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Settlement Indicators', 20, 20);

    doc.autoTable({
        startY: 25,
        head: [['Indicator', 'Value (0-10 scale)']],
        body: [
            ['Population Density', (villageData.settlement?.population_density || 0).toString()],
            ['Households', (villageData.settlement?.households || 0).toString()],
            ['Distance from Shore', (villageData.settlement?.distance_from_shore || 0).toString()],
            ['Infrastructure Score', (villageData.settlement?.infrastructure_score || 0).toString()]
        ],
        theme: 'grid',
        headStyles: { fillColor: [20, 184, 166] }
    });

    // Recommendations
    const finalY2 = doc.lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Recommendations', 20, finalY2);

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    let yPos = finalY2 + 10;

    const recommendations = [
        'Monitor weather forecasts regularly',
        'Review evacuation routes with family members',
        'Maintain emergency kit with essential supplies',
        'Register for SMS weather alerts',
        'Stay informed about local disaster management plans'
    ];

    recommendations.forEach((rec, index) => {
        doc.text(`${index + 1}. ${rec}`, 25, yPos);
        yPos += 7;
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(128, 128, 128);
        doc.text(
            `Generated by Hydro Hub | Page ${i} of ${pageCount}`,
            pageWidth / 2,
            doc.internal.pageSize.height - 10,
            { align: 'center' }
        );
    }

    // Save the PDF
    doc.save(`${villageData.village.name}_Risk_Report.pdf`);
};

export const generateSafetyGuidePDF = (villageData) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // Header
    doc.setFillColor(239, 68, 68); // Red
    doc.rect(0, 0, pageWidth, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text('Safety & Preparedness Guide', 20, 25);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text(`${villageData.village.name}, ${villageData.village.district}`, 20, 55);

    // Emergency Contacts
    doc.setFontSize(14);
    doc.text('Emergency Contact Numbers', 20, 70);

    doc.autoTable({
        startY: 75,
        head: [['Service', 'Contact Number']],
        body: [
            ['Disaster Management', '1078'],
            ['Police', '100'],
            ['Ambulance', '108'],
            ['Fire Service', '101'],
            ['Coast Guard', '1554']
        ],
        theme: 'grid',
        headStyles: { fillColor: [239, 68, 68] }
    });

    // Emergency Kit Checklist
    doc.addPage();
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Emergency Kit Checklist', 20, 20);

    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');
    let yPos = 30;

    const kitItems = [
        'First aid supplies',
        'Flashlights and batteries',
        'Important documents (waterproof bag)',
        'Cash',
        'Medications (7-day supply)',
        'Non-perishable food',
        'Drinking water',
        'Mobile phone + charger',
        'Whistle',
        'Blankets'
    ];

    kitItems.forEach((item, index) => {
        doc.text(`[ ] ${item}`, 25, yPos);
        yPos += 7;
    });

    // Save
    doc.save(`${villageData.village.name}_Safety_Guide.pdf`);
};
